```{r prologue, include=FALSE}
library(knitr)
library(e1071)
library(dplyr)
library(lattice)
library(ggplot2)
library(vcd)
library(vcdExtra)

knitr::opts_chunk$set(warning = FALSE
                      , message = FALSE
                      , echo = FALSE
                      , cache = TRUE
                      )

knitr::opts_template$set(
  fig.wide = list(fig.height = 4.5, fig.width = 8, fig.align='center')
  , fig.wideX = list(fig.height = 3, fig.width = 9, fig.align='center')
  , fig.relaxed = list(fig.height = 6, fig.width = 8, fig.align='center')
  , fig.tile = list(fig.height = 3, fig.width = 3, fig.align='center')
)
source("interpret_basics_theme.R")
```

---
title: "Exploratory Analysis of ICDM datasets"
author: "Julian Hatwell"
date: `r format(Sys.time(), "%b %Y")`
output: html_document
---
```{r load_data}
source("general_setup.R") # these are the sub samples where necessary

dsets <- data.frame(
  dnames = c("accident", "adult", "bankmark", "car", "cardiotography", "credit" , "german", "lending", "nursery", "rcdv")
  , class_cols = c("Accident_Severity", "income", "y", "acceptability", "NSP", "A16", "rating", "loan_status", "decision", "recid")
  , stringsAsFactors = FALSE
  )
source("load_complexity_results.R")
```

# Exploratory data analysis

```{r, opts.label='fig.wideX'}
for (j in 1:2) {
  dname <- dsets$dnames[j]
  class_col <- dsets$class_cols[j]
  
  print(paste("Exploratory Analysis for", dname, "with target variable", class_col))
        
  dat <- get(dname)
  cats <- sapply(dat, class)
  facs <- names(dat)[cats == "factor" & names(dat) != class_col]
  nums <- names(dat)[cats %in% c("numeric", "integer") & names(dat) != class_col]
  
  summary(dat)

  print(complexity_measures[dname, ])
  
  dnp <- list()
  bwp <- list()
  
  for (i in seq_along(cats)) {
    if (names(dat)[i] != class_col) {
      if (cats[i] == "factor") {
        if (length(levels(dat[[i]])) <= 8) {
            fmla <- as.formula(paste(names(dat)[i]
                                     , "~", class_col))
      mosaic(fmla, data = dat
             , rot_labels = c(45, 0, 0, 0))      
      }
    print(paste("Association statistics for", class_col, "and", names(dat)[i]))
    print(assocstats(table(dat[[i]], dat[[class_col]]))$chisq_tests)
      } else {
          fmla <- as.formula(paste("~", names(dat)[i]))
          dnp[[names(dat)[i]]] <- densityplot(fmla, data = dat
                                                , main = paste("Density of", names(dat)[i])
                                                , par.settings = MyLatticeTheme
             , strip = MyLatticeStrip)
          
          
          fmla <- as.formula(paste(names(dat)[i], "~", class_col))
          bwp[[names(dat)[i]]] <- bwplot(fmla, data = dat
                                                , main = paste("Boxplot of", names(dat)[i], "by", class_col)
                                                , par.settings = MyLatticeTheme
             , strip = MyLatticeStrip)
          
          if (skewness(dat[[i]]) > 1) {
            fmla <- as.formula(paste("~ log(", names(dat)[i], ")"))
            dnp[[paste0("log(", names(dat)[i], ")")]] <- densityplot(fmla, data = dat
                                                  , main = paste0("Density of log(", names(dat)[i], ")")
                                                  , par.settings = MyLatticeTheme
             , strip = MyLatticeStrip)
            
            fmla <- as.formula(paste0("log(", names(dat)[i], " + 1 - abs(min(", names(dat)[i], "))) ~ ", class_col))
            bwp[[paste0("log(", names(dat)[i], ")")]] <- bwplot(fmla, data = dat
                                                  , main = paste0("Boxplot of log(", names(dat)[i], ") vs ", class_col)
                                                  , par.settings = MyLatticeTheme
             , strip = MyLatticeStrip)
          }
        }
      } 
    }
  for (d in names(dnp)) {
  print(d)
  print(dnp[[d]])
  print(bwp[[d]])
  }
}
```


```{r eda_adult, opts.label='fig.wideX', eval=FALSE}
summary(adult)

cats <- sapply(adult, class)
dnp <- list()
bwp <- list()
for (i in seq_along(cats)) {
  if (names(adult)[i] != "income") {
    if (cats[i] == "factor") {
      if (length(levels(adult[[i]])) <= 8) {
          fmla <- as.formula(paste(names(adult)[i]
                                   , "~ income"))
    mosaic(fmla, data = adult
           , rot_labels = c(45, 0, 0, 0))      
    }
  print(paste("Association statistics for income and", names(adult)[i]))
  print(assocstats(table(adult[[i]], adult$income))$chisq_tests)
    } else {
        fmla <- as.formula(paste("~", names(adult)[i]))
        dnp[[names(adult)[i]]] <- densityplot(fmla, data = adult
                                              , main = paste("Density of", names(adult)[i])
                                              , par.settings = MyLatticeTheme
           , strip = MyLatticeStrip)
        
        
        fmla <- as.formula(paste(names(adult)[i], "~ income"))
        bwp[[names(adult)[i]]] <- bwplot(fmla, data = adult
                                              , main = paste("Boxplot of", names(adult)[i])
                                              , par.settings = MyLatticeTheme
           , strip = MyLatticeStrip)
        
        if (skewness(adult[[i]]) > 1) {
          fmla <- as.formula(paste("~ log(", names(adult)[i], ")"))
          dnp[[paste0("log(", names(adult)[i], ")")]] <- densityplot(fmla, data = adult
                                                , main = paste0("Density of log(", names(adult)[i], ")")
                                                , par.settings = MyLatticeTheme
           , strip = MyLatticeStrip)
          
          fmla <- as.formula(paste("log(", names(adult)[i], " + 1 - abs(min(", names(adult)[i], "))) ~ income"))
          bwp[[paste0("log(", names(adult)[i], ")")]] <- bwplot(fmla, data = adult
                                                , main = paste0("Boxplot of log(", names(adult)[i], ") vs income")
                                                , par.settings = MyLatticeTheme
           , strip = MyLatticeStrip)
        }
    }
  } 
}
for (d in names(dnp)) {
  print(d)
  print(dnp[[d]])
  print(bwp[[d]])
}
```

